import { useNavigate } from 'react-router-dom';
import { ResponsiveLayout } from '../components/ResponsiveLayout';

export function TermsOfServicePage() {
  const navigate = useNavigate();

  return (
    <ResponsiveLayout>
      <div className="privacy-page">
        <header className="privacy-header">
          <button onClick={() => navigate(-1)} className="back-button">
            ← Back
          </button>
          <h1>Terms of Service</h1>
        </header>

        <div className="privacy-content">
          <p className="last-updated">Last updated: February 2026</p>

          <section className="privacy-section highlight">
            <h2>Important Health & Safety Disclaimer</h2>
            <p>
              <strong>Flexer provides AI-generated workout plans for informational purposes only.
              These plans are not a substitute for professional medical advice, diagnosis, or
              treatment.</strong>
            </p>
            <p>
              Always consult a qualified healthcare provider before starting any new exercise
              program, especially if you have pre-existing medical conditions, injuries, or
              other health concerns. Never disregard professional medical advice or delay seeking
              it because of something you read or receive through Flexer.
            </p>
          </section>

          <section className="privacy-section">
            <h2>Assumption of Risk</h2>
            <p>
              Physical exercise carries inherent risks, including but not limited to muscle
              strains, joint injuries, cardiovascular events, and other physical harm. By using
              Flexer, you voluntarily assume all risks associated with participating in any
              exercise program, including those generated by AI.
            </p>
            <p>
              You acknowledge that:
            </p>
            <ul>
              <li>AI-generated workout plans may not account for your complete medical history</li>
              <li>The AI cannot assess your real-time physical condition or form</li>
              <li>Workout intensity and exercise selection may not be appropriate for your individual fitness level</li>
              <li>You are solely responsible for exercising safely and within your own limits</li>
              <li>You should stop any exercise that causes pain, discomfort, or unusual symptoms immediately</li>
            </ul>
          </section>

          <section className="privacy-section">
            <h2>Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by applicable law, Flexer, its creators, operators,
              and affiliates shall not be liable for any injury, illness, death, loss, or damage
              of any kind arising from or related to:
            </p>
            <ul>
              <li>Your use of or reliance on any AI-generated workout plan</li>
              <li>Participation in any exercise or physical activity recommended by the app</li>
              <li>Any inaccuracy, error, or omission in workout content generated by AI</li>
              <li>Your failure to consult a healthcare professional before beginning exercise</li>
            </ul>
            <p>
              In no event shall Flexer's total liability to you exceed the amount you have paid
              to use the service in the twelve months preceding the claim, or $0 if you have used
              the free tier.
            </p>
          </section>

          <section className="privacy-section">
            <h2>No Medical Relationship</h2>
            <p>
              Use of Flexer does not create a doctor-patient, therapist-client, or any other
              professional health relationship. Flexer is a fitness technology tool, not a
              medical service. The information provided is general in nature and may not apply
              to your specific circumstances.
            </p>
          </section>

          <section className="privacy-section">
            <h2>AI-Generated Content</h2>
            <p>
              Workout plans in Flexer are generated by third-party AI systems (such as ChatGPT,
              Claude, or Gemini). Flexer does not guarantee the accuracy, completeness, safety,
              or suitability of AI-generated content. The quality of your plan depends on the AI
              system you use and the information you provide during onboarding.
            </p>
            <p>
              You are responsible for reviewing your workout plan and making your own judgment
              about whether it is appropriate for you before beginning.
            </p>
          </section>

          <section className="privacy-section">
            <h2>Eligibility</h2>
            <p>
              You must be at least 18 years old to use Flexer. By using the app you represent
              that you are of legal age and have the legal capacity to agree to these terms.
            </p>
          </section>

          <section className="privacy-section">
            <h2>Changes to These Terms</h2>
            <p>
              We may update these terms from time to time. Continued use of Flexer after changes
              are posted constitutes your acceptance of the revised terms. We encourage you to
              review this page periodically.
            </p>
          </section>

          <section className="privacy-section">
            <h2>Contact</h2>
            <p>
              If you have questions about these terms, please reach out through the app or at the
              contact information provided on our website.
            </p>
          </section>
        </div>
      </div>
    </ResponsiveLayout>
  );
}
